${RGGEN_VHDL_RTL_ROOT}/rggen_rtl.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_or_reducer.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_mux.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_bit_field.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_bit_field_w01trg.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_address_decoder.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_register_common.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_default_register.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_indirect_register.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_external_register.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_adapter_common.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_apb_adapter.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_apb_bridge.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_axi4lite_skid_buffer.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_axi4lite_adapter.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_axi4lite_bridge.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_avalon_adapter.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_avalon_bridge.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_wishbone_adapter.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_wishbone_bridge.vhd
${RGGEN_VHDL_RTL_ROOT}/rggen_native_adapter.vhd
